import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Portfolio from '@/components/portfolio'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
      <div className='home-container'>
            <div className="row">
                <div className="col-sm-12 col-lg-12 p-0">
                    <div className="jumbotron">
                        <div className="row">
                            <div id='homeText' className="col-sm-10 col-md-6 col-lg-4 bioText">
                                <p className="fs-1 headFont">Josh Dale</p>
                                <div className='fs-6 text-white'>Full Stack Web Developer leveraging a Bachelor's
                                degree in Media Communications from Asbury University to create a 
                                synergy in technical skills and people. Five years in the coffee industry 
                                working in customer service, wholesale, cafe management, and employee training.</div>
                                <a href='blog' className="btn text-light" role="button">Read my blog »</a>
                            </div>
                        </div>
                    </div>
                </div>
                <Portfolio />

            </div>
            {/* <div className="row home-bottom">
                <div className="col">

                </div>
            </div> */}

        </div>
      </main>
    </>
  )
}
